### ISSUE TITLE
Issue by changing the filter mode

### ISSUE THREAD

**Issue by Yulquen** [jhbruhn/ambika-smr4-multimode#1]
Hi there, I have done a run of the voice card at JLCPCB with SMT assembly for most of the components, and I have some weird issues.

Right now the voicecard is connected with dupont cables to the motherboard and it is running (I get NICE sound out of it), but the 4052D is getting really hot when I change the filter mode (e.g. from BP to HP, but it can from any other direction) and the audio stop. I have to unplug and replug the -8V supply voltage to get it running again. I have the same issue with 3 voice cards I tested so far. 

For the 4052D I selected one from NEXPERIA (SKU= C11350) I think the qualiy should be fine. I have more doubts about the 2N7002 from Changjiang (https://lcsc.com/product-detail/MOSFET_Changjiang-Electronics-Tech-CJ-2N7002_C8545.html).

Any idea? Should I change one the IC or transistor mentionned above? Or any other components to focus on?

Thx

**Comment by jhbruhn** [comment]
Nice to hear from people making the boards! 

The problem you're having is strange though. I used a TI 4052BM (SKU C6521) and the same 2n7002 as you (as those were the ones provided as Basic Parts at the time) and my filter works fine. 

To get this clear: Changing modes leads to problems, and then you unplug and replug the -8V rail and then that filter-mode works as expected?

**Comment by jhbruhn** [comment]
I just checked the Datasheet for the 4052D you used: It's maximum voltage rating (VEE-VCC) is 10V ("Wide analog input voltage range from−5 V to +5 V").
The voicecard has a voltage of +-8V -> 16V (VEE-VCC). Thus I am surprised that it works that even though the voltage is exceeded by 6V!

Try replacing that 74HC4052 with a CD4052, the prefix is important here. I think that should fix the issue. I will try to improve the documentation a bit :)

**Comment by Yulquen** [comment]
Hi, thanks for the quick reply. 

I was also diving in the datasheet of the 4052B from NEXPERIA, and yes I think the issue is the maximal input voltage.

So I will buy a bunch of CD4052BM at mouser: https://www.mouser.de/ProductDetail/595-CD4052BM

And I think it should be fine. I will let you know.

Thanks again!

**Comment by Yulquen** [comment]
So replacing by CD4052BM has solved the issue. Thanks for the support
