### ISSUE TITLE
ISP connector

### ISSUE THREAD

**Issue by Yulquen** [jhbruhn/ambika-smr4-multimode#2]
ISP port and C35 are really close to each others. I can connect my programmer but it pushes a bit the capacitor on the side.
![PXL_20210409_180447338](https://user-images.githubusercontent.com/4542831/114223134-be6a7700-996f-11eb-8249-bc4d461cb3e9.jpg)

**Comment by jhbruhn** [comment]
Ah, I didn't really account for that as my header is smaller. Fixed in HW v03!
Please don't hesitate to open any other issues you may find :) Or just send pictures/demos of your Voicecards, I'd love to integrate them here :) 
maybe it's time to write a proper Readme.
